[package]
name = "weefee"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
dbus = "0.9.10"
networkmanager = "0.5"
ratatui = "0.29.0"
throbber-widgets-tui = "0.8"
tokio = { version = "1.48.0", features = ["full"] }
tui-input = "0.11.0"
